### ISSUE TITLE
Invalid PEM encoded certificate php 8.1 and laravel 10

### ISSUE THREAD

**Issue by muhammadjabir445** [codegreencreative/laravel-samlidp#143]
I am having the problem "Invalid PEM encoded certificate"
Following is the tracking error

I use PHP 8.1 and Laravel 10

#0 /var/www/test-sso-laravel-server/vendor/codegreencreative/laravel-samlidp/src/Traits/PerformsSingleSignOn.php(75): LightSaml\Credential\X509Certificate->loadPem()
#1 /var/www/test-sso-laravel-server/vendor/codegreencreative/laravel-samlidp/src/Traits/PerformsSingleSignOn.php(28): CodeGreenCreative\SamlIdp\Jobs\SamlSso->getCertificate()
#2 /var/www/test-sso-laravel-server/vendor/codegreencreative/laravel-samlidp/src/Jobs/SamlSso.php(48): CodeGreenCreative\SamlIdp\Jobs\SamlSso->init()
#3 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(76): CodeGreenCreative\SamlIdp\Jobs\SamlSso->__construct()
#4 /var/www/test-sso-laravel-server/vendor/codegreencreative/laravel-samlidp/src/Listeners/SamlLogin.php(23): CodeGreenCreative\SamlIdp\Jobs\SamlSso::dispatchSync()
#5 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): CodeGreenCreative\SamlIdp\Listeners\SamlLogin->handle()
#6 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#7 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\Events\Dispatcher->invokeListeners()
#8 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(745): Illuminate\Events\Dispatcher->dispatch()
#9 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(509): Illuminate\Auth\SessionGuard->fireLoginEvent()
#10 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(387): Illuminate\Auth\SessionGuard->login()
#11 /var/www/test-sso-laravel-server/app/Http/Controllers/AuthController.php(43): Illuminate\Auth\SessionGuard->attempt()
#12 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\AuthController->login()
#13 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#14 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#15 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#16 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route->run()
#17 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#20 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#22 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#24 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#26 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle()
#27 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#29 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#31 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\Pipeline\Pipeline->then()
#33 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack()
#34 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute()
#35 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute()
#36 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#37 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#38 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#40 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#41 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#43 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#44 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#46 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#48 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle()
#50 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle()
#52 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#54 /var/www/test-sso-laravel-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#55 /var/www/test-sso-laravel-server/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#56 {main}

**Comment by upwebdesign** [comment]
@muhammadjabir445, I would assume you have a `Invalid PEM encoded certificate`. Did you try to recreate your certificate?
